# Generated by Django 4.0.4 on 2022-07-28 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
